# Executed by make_model.py with its diagram helpers.
add('merge','Merge means reconciliation, then publication',
    'The live SQL merge uses operation intent, current target rows and checks. It does not replace the trunk COW root.',[
    N('frame',35,80,'Branch proposal — RAM',['Private images + effect frame','Before-images / fork sequence'],'branch',w=280,detail=['Workspace.frame supplies branch intent. First-touch witnesses and recorded target operations since fork_seq provide context. An ordinary SQL change without an agent operation can be treated as an opaque Assign based on its changed value.']),
    N('target',35,300,'Current target state',['Rows + recorded applied effects','Read versions / table counters'],'sql',w=280,detail=['The evaluator reads target rows and applied-operation history. It records a fingerprint so publication can refuse an evaluation whose involved tables or tracked premises moved afterward.']),
    N('resolve',365,80,'Resolve changed cells',['Compose compatible operations','Reject or report explicit loss'],'branch',w=280,detail=['No conflicting target effect: clean. Compatible Add/Add, Min/Min or Max/Max: compose. Equal Assign values converge. Different assignments default to Conflict; explicit LWW is incoming-merge-wins and reports discarded effects.']),
    N('gate',695,80,'Check admission',['WHERE guards on pre-state','Read premises; supplied assertions'],'check',w=280,detail=['Guards check the target before this branch\'s effects. Assertions check proposed results, but ordinary MERGE supplies none; SIMULATE supplies declared assertions. Exact read checking is limited to tracked runtime versions; predicate-only reads are not automatically quarantined.']),
    N('decision',1020,80,'Decision',['Conflict?','Gate passes?'],'check',w=150,h=110),
    N('held',1020,300,'No publish',['Conflict: retain','Gate: quarantine'],'check',w=150,h=110,detail=['Conflict leaves the branch available for correction. A failing admission gate in production MERGE quarantines the branch. Neither path applies the proposed row batch.']),
    N('preflight',695,300,'Recheck and preflight',['Refuse stale fingerprint','Validate all row / schema plans'],'check',w=280,detail=['Table counters catch changes between evaluation and publication. This check is different from validating every read made throughout the branch lifetime. Whole-plan preflight prevents known shape/constraint refusals from partially applying schema plans.']),
    N('ddl',365,300,'Apply schema edits first',['Outside the row transaction','May remain after later failure'],'check',w=280,detail=['Schema work runs before the row transaction. An unexpected I/O failure can leave schema effects even when row publication does not complete; the lifecycle is not a single crash-atomic operation.']),
    N('txn',365,540,'One ordinary transaction',['BEGIN → every accepted row','COMMIT once; abort on error'],'wal',w=280,h=120,detail=['All accepted row writes share one TxnManager transaction. This is the tested atomic row batch. Row publication uses ordinary heap/MVCC/WAL rather than making a branch root the shared table root.']),
    N('record',695,540,'Record published history',['Operations / versions / authors','Attest merge; then seal branch'],'lifecycle',w=280,h=120,detail=['Applied-operation history and logical row authorship are recorded after commit; physical version-author stamps can be written during row application. These separate provenance writes are not covered by the row WAL atomicity. Sealing then reclaims or retires branch state. A later failure cannot retroactively undo a committed row transaction.']),
    N('heap',35,540,'Shared SQL heap',['Accepted rows become visible','Subject to reader snapshot'],'sql',w=280,h=120)
    ],[
    E('frame','resolve',[[315,135],[365,135]],'intent',340,121,'branch'),
    E('target','resolve',[[175,300],[175,235],[505,235],[505,190]],'target + witnesses',350,221,'sql'),
    E('resolve','gate',[[645,135],[695,135]],'result',670,121,'branch'),
    E('gate','decision',[[975,135],[1020,135]],'checks',998,121,'check'),
    E('decision','held',[[1135,190],[1135,300]],'refuse',1140,245,'check'),
    E('decision','preflight',[[1060,190],[1060,255],[835,255],[835,300]],'eligible',940,241,'check'),
    E('preflight','ddl',[[695,355],[645,355]],'valid',670,342,'check'),
    E('ddl','txn',[[505,410],[505,540]],'then rows',505,480,'wal'),
    E('txn','heap',[[365,600],[315,600]],'rows',340,586,'sql'),
    E('txn','record',[[645,600],[695,600]],'then',670,586,'lifecycle')
    ],lanes=[L(345,490,320,205,'ATOMIC BOUNDARY: ROW TRANSACTION','wal')],height=735,
    cards=[
    C('Arithmetic example','Start at qty 20. A captures Add(−5); B captures Add(−3). Merge A → 15; merge B applies −3 to current 15 → 12. Use point UPDATEs without a prior stale explicit SELECT; additional checks can still refuse a merge.','branch'),
    C('Precondition versus postcondition','Two −12 withdrawals from 20: WHERE qty >= 12 rejects the second at current qty 8. WHERE qty >= 0 allows it and can produce −4. An explicit postcondition would test the proposed final value.','check'),
    C('What is not atomic together','DDL, the row transaction, provenance/history recording and branch sealing are distinct stages. Frame retry deduplication does not establish exactly-once whole-merge retries after a crash.','wal')],
    table={'headers':['Cell outcome','Meaning','Publication'], 'rows':[
    ['Clean','No incompatible concurrent operation, or equal assignments','Eligible if checks pass'],['Commuting','Supported operations compose','Eligible if checks pass'],['Conflict','Incompatible operations / row conflict','No rows published'],['ResolvedWithLoss','Explicit incoming-wins policy discards a competing effect','Loss reported; checks still apply']]},sources=[
    S('src/agent_sql/merge_engine.rs',199,'Operation resolution'),S('src/agent_sql/runtime.rs',4269,'Evaluation'),S('src/agent_sql/runtime.rs',4562,'Guard pre-state'),S('src/agent_sql/gate.rs',278,'Read-premise finding'),S('src/agent_sql/runtime.rs',4894,'Publication stages'),S('src/agent_sql/runtime.rs',5168,'Atomic row transaction'),S('tests/guard_precondition_probe.rs',288,'Weak guard can allow negative result')])

add('wal','WAL, commit, crash recovery',
    'For ordinary heap transactions, durable log records permit table pages to be written later. Log order matters.',[
    N('change',45,90,'Ordinary row change',['Append physical WAL record','Modify RAM page; set page LSN'],'sql',w=250,detail=['Heap insert/delete/update routines append records and update pages with the corresponding log position. This flow does not mean every schema, index, allocator or COW page mutation is journaled identically.']),
    N('commit',345,90,'COMMIT',['Append Commit record','Flush WAL through its LSN'],'wal',w=250,detail=['TxnManager flushes through the commit LSN before reporting success. It then records transaction end and removes the transaction from the active set. Committing does not require every dirty table page to have reached disk.']),
    N('logdisk',645,90,'Durable WAL bytes',['write + sync_data','Commit can now be acknowledged'],'wal',w=250,detail=['WAL uses ordered records with lengths/checksums and a flushed position. The flush path keeps ordering under synchronization; a higher durable watermark must not skip earlier unsynced records.']),
    N('flush',945,90,'Later page write',['Flush WAL through page LSN','Then write dirty heap page'],'sql',w=210,detail=['The buffer pool\'s WAL gate runs before dirty-page flush/eviction. It recognizes ordinary page LSN formats; it is not a universal journal for separate branch metadata and COW pages.']),
    N('scan',45,370,'On restart: scan WAL',['Read complete valid records','Find committed / unfinished txns'],'wal',w=250,detail=['Recovery scans valid records, initializes transaction ID state, and reconstructs which transactions committed or ended. A torn tail is different from complete transaction recovery.']),
    N('redo',345,370,'Redo heap changes',['Replay row records and CLRs','Skip already-covered page LSNs'],'wal',w=250,detail=['The page LSN makes physical redo repeatable. Redo reconstructs logged history, including work that may later be undone if its transaction did not commit.']),
    N('undo',645,370,'Undo unfinished work',['Walk transaction log chains','Write compensation records'],'wal',w=250,detail=['Abort/recovery writes CLRs with undo-next pointers so a second crash can continue undo rather than blindly applying the same inverse twice.']),
    N('finish',945,370,'Repair and reopen',['Repair heap directories','CLI: rebuild indexes, checkpoint'],'sql',w=210,detail=['CLI calls rebuild_indexes and checkpoint after recovery. The pgserver example opens after recover but does not run that same rebuilding block. This entrypoint difference is explicit in the next view.'])
    ],[
    E('change','commit',[[295,145],[345,145]],'commit',320,131,'wal'),
    E('commit','logdisk',[[595,145],[645,145]],'fsync',620,131,'wal'),
    E('logdisk','flush',[[895,145],[945,145]],'later',920,131,'sql',True),
    E('logdisk','scan',[[770,200],[770,285],[170,285],[170,370]],'after crash: recover from log',460,271,'wal'),
    E('scan','redo',[[295,425],[345,425]],'analyze',320,411,'wal'),
    E('redo','undo',[[595,425],[645,425]],'then',620,411,'wal'),
    E('undo','finish',[[895,425],[945,425]],'repair',920,411,'sql')
    ],lanes=[L(25,30,1150,205,'RUNNING: ORDINARY HEAP TRANSACTION','wal'),L(25,310,1150,210,'RESTART: REPEATABLE REDO, THEN LOSER UNDO','wal')],height=560,
    cards=[C('Checkpoint shortens recovery','With no active transactions, checkpoint flushes WAL, flushes pages, syncs the database, then truncates eligible WAL and redeclares schema/run state. Retention pins can prevent discarding consumer-needed history.','wal'),C('What the crash test proves','The focused merge test kills a process mid-row-publication and checks all-before or all-after rows. It does not simulate loss of the operating system page cache during machine power failure.','check'),C('COW has a different local rollback tool','CowTree WriteJournal restores in-place pages after one tree-operation error and delays retirement. It is not this WAL transaction and does not make all branch sidecars crash-atomic.','branch')],sources=[
    S('src/wal/txn.rs',608,'Commit flush ordering'),S('src/buffer/buffer_pool.rs',1425,'WAL-before-page gate'),S('src/wal/recovery.rs',5,'Redo and undo'),S('src/wal/txn.rs',651,'Compensation-based abort'),S('src/wal/txn.rs',802,'Checkpoint'),S('src/cow/btree.rs',147,'Tree write journal'),S('tests/integration_crash_safety.rs',12,'Process-crash test scope')])

add('persistence','What is on disk, and what reopening restores',
    'Different files and buffer pools create different durability boundaries. Persisted components do not imply a restored agent session.',[
    N('main',45,80,'Main database file: <db>',['Ordinary catalog / heap / indexes','Branch COW arena pages'],'sql',w=320,detail=['The main buffer pool caches both regions. Ordinary allocation is below a persisted arena floor; ArenaPageStore owns extents above it. The default new-database headroom is 32,736 ordinary pages, a real growth bound.']),
    N('wal',440,80,'<db>.wal',['Ordinary row recovery log','Transaction and control records'],'wal',w=320),
    N('catalog',835,80,'<db>.branchcat',['Branch records / roots / indexes','Separate file and buffer pool'],'branch',w=320,detail=['TableBranchCatalog stages indexed record changes and group-commits its own pool/file. Its catalog root and each stored branch root are separate concepts. Catalog fsync does not itself flush the main pool\'s COW data pages.']),
    N('arena',45,295,'<db>.arena',['Allocation and ownership state','Not the private row payloads'],'lifecycle',w=320,detail=['This allocator checkpoint/tail records the arena floor, extents, ownership and pending frees. COW row bytes remain in the main database file. Reopen avoids reissuing already-owned extents.']),
    N('tel',440,295,'<db>.tel — CLI',['Typed effect frames and guards','Appended; replayable as frames'],'wal',w=320,detail=['The CLI constructs DurableEffectLog. The PostgreSQL-wire example constructs MemEffectLog. Replayed frames can feed a separate effect merger; they do not reconstruct the live SQL Workspace.']),
    N('prov',835,295,'<db>.provenance — CLI',['Run dictionary / version stamps','Logical row authorship'],'lifecycle',w=320,detail=['The CLI attaches DurableProvenanceStore. The server example leaves the runtime\'s default memory store. Provenance append durability is separate from row WAL commit.']),
    N('boot',45,530,'Startup order',['DbLock → recovery → catalog','Open branch catalog and allocator'],'neutral',w=320,detail=['DbLock excludes a second process writing the same database. Ordinary catalog allocation must precede choosing the arena floor. Reopen uses the stored floor; it does not guess a new boundary over existing extents. CLI additionally rebuilds ordinary indexes after recovery.']),
    N('attach',440,530,'Reattach storage',['Validate existing COW root','Start reaper; replay CLI sidecars'],'branch',w=320,detail=['A missing or invalid recorded root is refused rather than silently replaced. LeaseThread resumes interrupted reaps. CLI effect/provenance replay restores those stores, not all runtime maps.']),
    N('ram',835,530,'Fresh runtime memory',['No recovered private Workspace','No restored escrow / read history'],'check',w=320,detail=['reopen_with_storage constructs State::default. Branch names, workspaces, applied-operation history, merge records, read dependencies and escrow are not rehydrated into an unfinished SQL session. Durable roots alone cannot make it resumable.'])
    ],[
    E('main','arena',[[205,190],[205,295]],'allocation sidecar',205,248,'lifecycle',True),
    E('catalog','main',[[995,80],[995,30],[205,30],[205,80]],'branch root IDs address main-file pages',600,22,'branch'),
    E('boot','attach',[[365,585],[440,585]],'reopen',402,571,'branch'),
    E('attach','ram',[[760,585],[835,585]],'fresh RAM',797,571,'check')
    ],height=680,cards=[C('Root publication is a separate boundary','set_root writes branch metadata in the catalog pool. It is not an atomic commit across COW data, allocator state, effect log, provenance and shared heap.','check'),C('Two shipped entrypoints differ','The CLI wires durable TEL/provenance and index rebuilding after recovery. examples/pgserver.rs uses memory TEL/provenance and lacks the CLI index-rebuild block. The map describes both, not an idealized common configuration.','check')],
    table={'headers':['Component','CLI','pgserver example'], 'rows':[
    ['Main heap / WAL / arena / branch catalog','Page/file-backed','Page/file-backed'],['Effect log (TEL)','DurableEffectLog → .tel','MemEffectLog'],['Provenance','DurableProvenanceStore → .provenance','Memory store'],['Index rebuild after WAL recovery','Explicitly called','No corresponding call'],['Unfinished agent Workspace restored','No','No']]},sources=[
    S('src/cli/cli.rs',46,'CLI construction'),S('examples/pgserver.rs',61,'Server construction'),S('examples/pgserver.rs',112,'Memory effect log wiring'),S('src/branch/table_catalog.rs',176,'Separate catalog pool'),S('src/branch/arena.rs',1466,'Allocator persistence'),S('src/agent_sql/runtime.rs',1381,'Reopen creates fresh runtime state'),S('src/provenance/durable.rs',38,'Provenance file contents')])
